### ISSUE TITLE
Using old dump1090?

### ISSUE THREAD

**Issue by FoxxMD** [Thom-x/docker-fr24feed-piaware-dump1090#1]
Just wondering why this docker uses mutability/dump1090 instead of https://github.com/flightaware/dump1090 ?

**Comment by Thom-x** [comment]
I don't know, I should give it a try.

Maybe I tried to make it work with the first repo I found.

**Comment by ShoGinn** [comment]
If you are looking for a similar repo but for arm.. 
https://github.com/ShoGinn/docker-ads-b
I think you are on the right path ;) enjoyed seeing the repo in Unraid

**Comment by Thom-x** [comment]
Fixed d329c4ed2eac1b70b0897ab160aa157ec212e2c2
