### ISSUE TITLE
Question about MLAT

### ISSUE THREAD

**Issue by Autotren** [Thom-x/docker-fr24feed-piaware-dump1090#100]
Hello, I wasn't sure where to ask this question, but I decided to post it here since I'm running this container.

A couple of days ago I set up my receiver, and to my satisfaction, the local dump1090 interface doesn't have any problems showing MLAT tracks of local flight school (C152) traffic (when in range). For this reason, I'm puzzled as to why those airplanes do not show up either on FlightAware, FlightRadar24, or ADSBexchange. Both FlightAware and ADSBexchange show the receiver MLAT as up and synchronised.

Edit: Additionally, it is clear by looking at my stats that at least FlightAware is receiving MLAT positions, maybe they hide all GA traffic in Spain or something...
![image](https://user-images.githubusercontent.com/43890730/201680859-aefe8066-d4bc-4cd3-bcbb-6a753a02b966.png)
If this is the case, my question would be why doesn't it appear on ADSBexchange, as they claim not to "censor" anything, is it perhaps because of the lower number of feeders they have?

**Comment by Thom-x** [comment]
Hi, it's probably the number of feeders.
Before I setup a better antenna I received MLAT but I was not synchronized with other receivers. Now with a better one it's much better specially on adsbex.
