### ISSUE TITLE
How to hide the sidebar on mobile devices?

### ISSUE THREAD

**Issue by therealhalifax** [Thom-x/docker-fr24feed-piaware-dump1090#102]
## Specifications

  - Image hash or version: 1.18.0.2
  - Platform: HA OS
  - Subsystem:

## Expected Behavior
hide sidebar to see the map on mobile devices

## Actual Behavior
sidebar overlapping the whole screen and map could not be shown

## Steps to Reproduce the Problem

  1. open Addon frontend on mobile device with portrait screen
  1.
  1.

**Comment by Thom-x** [comment]
Hello, It's more a question for dump1090fa. I'm just copy/pasting what they do.

[RUN git clone -b ${DUMP1090_VERSION} --depth 1 https://github.com/flightaware/dump1090 && \](https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/blob/3fbad056dd976e77d06ef00d3509af7b327b2285/Dockerfile#L20)

You should ask them.
