### ISSUE TITLE
option to select USB device

### ISSUE THREAD

**Issue by Rothammel** [Thom-x/docker-fr24feed-piaware-dump1090#103]
I have two rtl devices, one for my 433MHz temperature sensors, and one for ADS-B Multi-Portal Feeder

**Comment by Thom-x** [comment]
You can select the one you want to share with replacing `--device=/dev/bus/usb:/dev/bus/usb \` with the exact usb port you want to use.

**Comment by Rothammel** [comment]
thx, but I was wrong, I use the Home Assistant addon from Max

**Comment by Thom-x** [comment]
In this case you should ask him to do that. I cannot change this parameter from here.

**Comment by martian** [comment]
You can set the serial numbers in the devices using rtl_eeprom (if your dongle has an eeprom). Those serials can be used to select the correct device in dump1090 and rtl_433. This also works in the Home Assistant addons.

I use serials 00000433 and 00001090.
For dump1090, set `DUMP1090_ADDITIONAL_ARGS = -device 00001090`
For rtl_433, edit rtl_433.conf[.template] and use:  `device :00000443`

**Comment by MaxWinterstein** [comment]
Owner of the add-on, aka Max here:


Providing dump1090 args can be archived using this field:

![image](https://user-images.githubusercontent.com/5927148/215416278-09eab305-a1b8-4348-91f2-b99ea82d28e7.png)

For reference: https://github.com/MaxWinterstein/homeassistant-addons/issues/134

**Comment by Rothammel** [comment]
Awesome, it works. thank you all so much

![image](https://user-images.githubusercontent.com/42540450/215557613-88262cd5-9eb6-47eb-97ca-eb2c94f62bbb.png)
![image](https://user-images.githubusercontent.com/42540450/215557703-d65159df-3414-4956-9bc8-846d503342ce.png)
![image](https://user-images.githubusercontent.com/42540450/215558129-5a4e6bfc-3bf6-4dfb-be6b-eba293d545f6.png)
