### ISSUE TITLE
Container crashing without any apparent reason

### ISSUE THREAD

**Issue by fl0wfr** [Thom-x/docker-fr24feed-piaware-dump1090#107]
## Specifications

  - Image hash or version: PR-106 and latest
  - Platform: amd64
  - Subsystem: 

## Expected Behavior
Simply start and feed FR24/PiAware

## Actual Behavior
Crash loop without any error

## Steps to Reproduce the Problem

  1. Start the container with this command: docker run -d -p 8080:8080 -p 8754:8754 \
	--device=/dev/bus/usb:/dev/bus/usb \
	-v "/etc/localtime:/etc/localtime:ro" \
	-e "FR24FEED_FR24KEY=<>" \
	-e "PIAWARE_FEEDER_DASH_ID=<>" \
	-e "HTML_SITE_LAT=<>" \
	-e "HTML_SITE_LON=<>" \
	-e "HTML_SITE_NAME=<>" \
	-e "SERVICE_ENABLE_ADSBEXCHANGE=false" \
	-e "MLAT_EXACT_LAT=<>" \
	-e "MLAT_EXACT_LON=<>" \
	-e "MLAT_ALTITUDE_MSL_METERS=<>" \
	-e "SERVICE_ENABLE_PLANEFINDER=false" \
	-e "TZ=Etc/GMT+0" \
	--tmpfs /run:exec,size=32M \
	--tmpfs /planefinder/log:exec,size=32M \
	--tmpfs /usr/lib/fr24/public_html/data:size=32M \
	--restart=unless-stopped \
	--network=myNetwork \
	--name fr24feed \
	thomx/fr24feed-piaware:PR-106
  2. USB Tuner is: Bus 002 Device 003: ID 0bda:2838 Realtek Semiconductor Corp. RTL2838 DVB-T

I've attached some logs.
[fr24feed.log](https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/files/10472514/fr24feed.log)

**Comment by Thom-x** [comment]
Could you try disabling services one by one to see the culprit ?

**Comment by Thom-x** [comment]
Ok, at least everything else is OK.
Could you try to start manually the HTTP server by executing the same command ? 
https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/blob/1afb9b3f971801f905abb9d70b036a290013326a/root/etc/s6-overlay/s6-rc.d/http/run#L5

**Comment by fl0wfr** [comment]
No return of the command, I don't have ps in the image so I can't check if it's running, but I doubt it runs. Also, no message in logs following the start of thttpd. And no access to the page with the published port.

**Comment by Thom-x** [comment]
Probably not working (it should be blocking). You coucld check the exit code `$?`.
Could you change the port by a random one `-p 4242`?

**Comment by fl0wfr** [comment]
Same issue with port 4242, and I get a "1" exit code.

**Comment by Thom-x** [comment]
Strange, I would suggest changing path, ports, etc to see what's wrong.
I'm not sure if I can help more. 😕

**Comment by fl0wfr** [comment]
Okay, seems strange, I just popped the container on a new host, no persistent storage, basic options. In the meantime I will run without the WebUI.
Thanks anyway!

**Comment by Thom-x** [comment]
Sorry for that :/

**Comment by fl0wfr** [comment]
No worries, you already did a great work, thanks!

**Comment by rpavlyuk** [comment]
I can confirm the same problem: as soon as you enable SERVICE_ENABLE_HTTP -- it crashes. Starting `thttpd` inside the container crashes it as well.

@Thom-x, if you can provide any instructions on how and where to check `thttpd` logs (I'm RedHat guy, not Debian :)) so I can troubleshot the issue.

**Comment by Thom-x** [comment]
>@Thom-x, if you can provide any instructions on how and where to check thttpd logs (I'm RedHat guy, not Debian :)) so I can troubleshot the issue.

`thttpd `is logging on stdout (no daemon), what strange is that I'm also using it on amd64 without error.

**Comment by Thom-x** [comment]
@Littlejth Did you try starting the container with only HTTPD enabled ?

**Comment by Littlejth** [comment]
With only the HTTP service enabled, it still just starts and stops again. Attached is the log file of a single time I attempted to start it after creating the container with only HTTP enabled.

[fr24feed-piaware.log](https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/files/10876407/fr24feed-piaware.log)

**Comment by Thom-x** [comment]
I created a branch to switch from thttpd to httpd, I'll let you now when the image is available so you can test and give me the feedback https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/pull/114.

**Comment by Thom-x** [comment]
You can test it with `docker pull thomx/fr24feed-piaware:PR-114`

**Comment by fl0wfr** [comment]
Hello Thom-x,
Same issue, and I see this message in logs:
`[http] /httpd-foreground: 7: exec: httpd: not found`

**Comment by Thom-x** [comment]
What is the content of `/usr/local/apache2/bin` it's probably not the same between different arch ?

**Comment by fl0wfr** [comment]
![Screenshot_20230304-173130-01](https://user-images.githubusercontent.com/12629116/222917642-b792d6c9-56f0-4ff5-991f-3ebb1dc56bdd.jpeg)

**Comment by Thom-x** [comment]
Ok funny, it's probably not compatible for all arch...
I need to find another candidate 😄.

**Comment by Littlejth** [comment]
It did start working on my aarch64 pi but obviously not a great solution if it doesn't work for AMD64 as well :)

**Comment by MaxWinterstein** [comment]
@fl0wfr which docker version are you running? v23?

Users of my _Home Assistant_ Add-On raised the same issue: https://github.com/MaxWinterstein/homeassistant-addons/issues/149

I guess, `thttpd` does what is explained here: https://developers.home-assistant.io/blog/2023/04/13/new_limits_for_add_ons/

>With Home Assistant OS 10, we update to the latest Docker release 23.0. With the new Docker version the maximum number of open file descriptors for add-ons changed to infinity (sort of).
> ...
> Also in all three cases, memory got allocated dynamically depending on the number of open file descriptors allowed (which can be determined via prlimit64 syscall, which returns a limit of 1073741816).

**Comment by fl0wfr** [comment]
@MaxWinterstein yes I'm using Docker 23.0.4

**Comment by MaxWinterstein** [comment]
@fl0wfr no linux memory expert here, but can you give the `ulimit` idea a try?

https://docs.docker.com/engine/reference/commandline/run/#ulimit

Something like
```bash
docker run --ulimit nofile= 1048576 ......
```

might be worth a shot

**Comment by fl0wfr** [comment]
@MaxWinterstein it works now. That should do the trick for now, thanks.

**Comment by MaxWinterstein** [comment]
@Thom-x this might hit more and more people who switch to docker 23

I created #118 as quickfix, but switching to some more recent webserver might be a better approach ;)

**Comment by Thom-x** [comment]
Thanks, I'll do a PR image for testing quickly and release of it's all good 👍 !

**Comment by MaxWinterstein** [comment]
> Thanks, I'll do a PR image for testing quickly and release of it's all good 👍 !

Awesome! Can't really test it myself here, hope it works 🤞

**Comment by fl0wfr** [comment]
You let me know and I will test it ;)

**Comment by CoMPaTech** [comment]
I still ran into issues with Max' update on his HA-addon. Still OOM errors on thttp. See screenshot in https://github.com/MaxWinterstein/homeassistant-addons/issues/149#issuecomment-1516359955 if helpful

**Comment by MaxWinterstein** [comment]
> I still ran into issues with Max' update on his HA-addon. Still OOM errors on thttp. See screenshot in [MaxWinterstein/homeassistant-addons#149 (comment)](https://github.com/MaxWinterstein/homeassistant-addons/issues/149#issuecomment-1516359955) if helpful

I guess the fix in my addon is placed wrongly. I think s6 starts the httpd stuff in another shell/session/thread/... where my adjustment is not read.

#118 is made a little bit different

**Comment by Thom-x** [comment]
You can try with the image `thomx/fr24feed-piaware:PR-118`

**Comment by fl0wfr** [comment]
It works, thank you :)

**Comment by Thom-x** [comment]
Nice 😄 let's do a release then.

**Comment by Thom-x** [comment]
It's now available with 1.21.0 or latest 👍

**Comment by TheDom42** [comment]
> It's now available with 1.21.0 or latest 👍

Running Unraid 6.11.5 (latest stable version), which has Docker v20.10.21.

At least on my system, this update to 1.21.0 does not seem to work. After I update, my (otherwise so far completely stable) container stops automatically without any error logged. This happens a few seconds after start of the container. 

Downgrading back to v1.20.0 fixes the issue, so I would assume, that this is related to this issue? If I have time later on, I can try the dedicated PR tag/image, if that gives a clearer picture.

**Comment by fl0wfr** [comment]
> > It works, thank you :)
> 
> @fl0wfr did you see any difference with the cpu usage?

No, around 3 and 7% CPU usage, running on a Celeron N5105.
