### ISSUE TITLE
New PiAware Update 8.2 Available

### ISSUE THREAD

**Issue by therealhalifax** [Thom-x/docker-fr24feed-piaware-dump1090#111]
my stats page mentioned a new update for PiAware to 8.2

![grafik](https://user-images.githubusercontent.com/63123435/215528633-ef1a529d-fc41-428d-9adc-b863d3a1a732.png)

**Comment by Thom-x** [comment]
Update is available with this tag :

`
docker pull thomx/fr24feed-piaware:PR-112
`

Let's see if it works well 👍
I'll merge it soon if OK.
