### ISSUE TITLE
OpenSKy

### ISSUE THREAD

**Issue by yousaf465** [Thom-x/docker-fr24feed-piaware-dump1090#121]
can it be included?
https://opensky-network.org/contribute/improve-coverage
since a HA integration exist for it.
https://www.home-assistant.io/integrations/opensky/

**Comment by Thom-x** [comment]
You can test it with image with tag `docker pull thomx/fr24feed-piaware:PR-124`, see setup on [README](https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/blob/feat/add-opensky-support/README.md#opensky)
