### ISSUE TITLE
Feature request - add adsb.fi to the list of feeders

### ISSUE THREAD

**Issue by crispy78** [Thom-x/docker-fr24feed-piaware-dump1090#123]
## Specifications

  - Image hash or version: 1.21
  - Platform: Home Assistant (https://github.com/MaxWinterstein/homeassistant-addons/tree/main/adsb-multi-portal-feeder)
  - Subsystem:

## Feature request

Since there is a lot of debate going online about the (controversial) sale of ADSBExchange.com. 
Would it be possible to add adsb.fi to the list of feeders? And would it also be possible to have both of them added to the default trackers? ADSBExchange.com and adsb.fi allow to view military aircraft by pressing the U.

**Comment by yousaf465** [comment]
https://github.com/adsbfi

**Comment by yousaf465** [comment]
@Shariner, if you help with this too?

**Comment by Thom-x** [comment]
Should be working with image `PR-132`
Minimal config to add:
```
      - "SERVICE_ENABLE_ADSBFI=true"
      - "ADSBFI_UUID=XXX" # generated from `cat /proc/sys/kernel/random/uuid`
      - "ADSBFI_STATION_NAME=XXX"
```

**Comment by yousaf465** [comment]
Waiting for the version to update @MaxWinterstein repo also needs to be updated.

**Comment by MaxWinterstein** [comment]
> [1.26.1] SERVICE_ENABLE_ADSBFI is missing in README : Configure : Common list of services

#136
