### ISSUE TITLE
OpenSky Username variable

### ISSUE THREAD

**Issue by Eurotimmy** [Thom-x/docker-fr24feed-piaware-dump1090#125]
Hi, I don't believe this is breaking anything. 

In the **README.md** and the **docker-compose.yml** files
I see one variable with a possible typo "MY_PENSKY_USERNAME"
Possibly intended to be named "MY_OPENSKY_USERNAME"

Thank you for all the work on this!!

**Comment by Thom-x** [comment]
Good catch 😄
