### ISSUE TITLE
MLAT on flightaware "Receiver location not configured"

### ISSUE THREAD

**Issue by yayitazale** [Thom-x/docker-fr24feed-piaware-dump1090#137]
## Specifications

  - Image hash or version: 1.27.0
  - Platform: RPI 3B+
  - Subsystem: Raspbian OS lite

## Expected Behavior

I have configured MLAT like this:
```
 - MLAT_EXACT_LAT=XX.XXXXXX
 - MLAT_EXACT_LON=-X.XXXXXX
 - MLAT_ALTITUDE_MSL_METERS=XX
```

I have also configured the environmental for FR24 to activate MLAT:
```
- FR24FEED_MLAT=yes
```

## Actual Behavior

Flightaware says: _Multilateration (MLAT): Supported / Receiver location not configured_. 

I'm not able to see anything regarding MLAT in the device page of FR24 neither.

https://www.flightradar24.com/account/feed-stats/?id=17127
https://flightaware.com/adsb/stats/user/surfobsession#stats-162765

What I'm doing wrong?

**Comment by Thom-x** [comment]
On my side it's working I added this to the config, could you try to see if it is better ?

```
      - "DUMP1090_ADDITIONAL_ARGS=--json-location-accuracy 2"
```

**Comment by yayitazale** [comment]
It still claims _Multilateration (MLAT): Supported / Receiver location not configured._

**Comment by Thom-x** [comment]
Strange, did you update the location on the website itself ?
![image](https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/assets/6797195/e181e9a3-d027-497d-873b-d4e45f97cbeb)

**Comment by yayitazale** [comment]
> Strange, did you update the location on the website itself ? ![image](https://user-images.githubusercontent.com/6797195/250906226-e181e9a3-d027-497d-873b-d4e45f97cbeb.png)

I never touched that, and yes, the lat/long were different? I changed them and now it is working, thanks.
