### ISSUE TITLE
Failed to start add-on under Home Assistant

### ISSUE THREAD

**Issue by pstoian** [Thom-x/docker-fr24feed-piaware-dump1090#140]
## Specifications

  - Image hash or version: ADS-B Multi-Portal Feeder // Current version: 1.27.2
  - Platform: Home Assistant Add-on
  - Subsystem:  Home Assistant Add-on

## Expected Behavior
After the last upgrade on 7/9/23 - to the version 1.27.2 - my system is giving me the following error and I caanot start the addon:

Failed to start add-on
Image ghcr.io/maxwinterstein/homeassistant-adsb-multi-portal-feeder-aarch64:1.27.2 does not exist for addon_f1c878cb_adsb-multi-portal-feeder

## Actual Behavior
Failed to start add-on
Image ghcr.io/maxwinterstein/homeassistant-adsb-multi-portal-feeder-aarch64:1.27.2 does not exist for addon_f1c878cb_adsb-multi-portal-feeder

## Steps to Reproduce the Problem

  1. Start the addon
  2. Geeting the error
  1.

**Comment by Thom-x** [comment]
You probably need to open the issue on the addon repo side.
