### ISSUE TITLE
Radarbox - 'already claimed' error on supplied sharing key

### ISSUE THREAD

**Issue by Eurotimmy** [Thom-x/docker-fr24feed-piaware-dump1090#145]
This may assist others when configuring for Radarbox.
I'm using Docker on an Unraid box but should be similar for other similar configurations.

When running the docker command (at [README.md](https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/blob/master/README.md#radarbox)) I recieved a sharing key... but it was listed as 'already claimed' and associated with another Radarbox account on the Radarbox website (in the [claim page](https://www.radarbox.com/sharing-data/claim)).

The support at Radarbox was kind to point out that I wasn't giving 'my MAC address' and only providing the 'docker container MAC address', such as this standard docker convention: **02:42**:a1:b2:c3:d4

To solve this I passed in my MAC address from eth0, by using the command below.
(change to your own MAC address)

#-----------------------------------------------------------#
docker run -it --rm **--mac-address A1:B2:C3:D4:E5:F6**
      -e "SERVICE_ENABLE_RADARBOX=true"
      -e "SERVICE_ENABLE_DUMP1090=false"
      -e "SERVICE_ENABLE_HTTP=false"
      -e "SERVICE_ENABLE_PIAWARE=false"
      -e "SERVICE_ENABLE_FR24FEED=false"
      -e "HTML_SITE_LAT=45"
      -e "HTML_SITE_LON=9"
      -e "HTML_SITE_ALT=0"
    thomx/fr24feed-piaware /bin/bash
#-----------------------------------------------------------#

Your MAC address?
- In Unraid is at 'Settings' > 'Network Settings' > 'Interface eth#'
or
- In Linux `ifconfig -a` will list your interface(s) and MAC(s)

**Comment by 73-de-LZ** [comment]
And if this dont help use the solution from [https://github.com/sdr-enthusiasts/docker-radarbox/blob/main/version_0.4.3_workarounds.md](url)

Exactly :
```
# make a directory to hold our fake data
mkdir -p /opt/adsb/data

# generate a fake cpuinfo file
# start by taking our current cpuinfo file
cp /proc/cpuinfo /opt/adsb/data/fake_cpuinfo

# ... and add a fake serial number to the end
echo -e "serial\t\t: $(hexdump -n 8 -e '4/4 "%08X" 1 "\n"' /dev/urandom | tr '[:upper:]' '[:lower:]')" >> /opt/adsb/data/fake_cpuinfo
```
and 
```
#after docker run command simply add 
-v /opt/adsb/data/fake_cpuinfo:/proc/cpuinfo \
```
