### ISSUE TITLE
ADSB exchange uuid generation.

### ISSUE THREAD

**Issue by aevela** [Thom-x/docker-fr24feed-piaware-dump1090#153]
Is there any alternative process for getting an ADSBexchange uuid?  The link https://www.adsbexchange.com/myip/gen-uuid/ appears to be dead. 

Great job, amazing docker container -- working straight out of the box.  Thank you.

**Comment by aevela** [comment]
Worked like a charm!

**Comment by Thom-x** [comment]
Perfect I'll update the doc
