### ISSUE TITLE
Please advice.

### ISSUE THREAD

**Issue by 73-de-LZ** [Thom-x/docker-fr24feed-piaware-dump1090#157]
Hello all! I am building remote station, which will be placed at a good remote place with a wide open horizon, but the 4G connection data plan is limited. So looking at the traffic of my home station i thinking about a solution to that problem. I want to ask is it will be possible to run only [dump1090-fa] with Skyaware on the remote place and run another station at the home location with Thom-x [docker-fr24feed-piaware-dump1090] to reduce the traffic. Remote and home have static IP and all possible port forwardings. I am just don't know if the Thom-x docker image could be configured to suit my needs and save the traffic bandwidth of the remote station, please advice.
![mlat-dump1090-diagram_design](https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/assets/16052106/334c878c-4bfb-45cb-b7d4-c414673d4c1a)

**Comment by Thom-x** [comment]
It's possible, I run mine like that. Only dump1090 on one side connected to the dongle, and on the other side dump1090 connecting to the remote dongle (net-only).

Dongle side:
```
      - "SERVICE_ENABLE_DUMP1090=true"
      - "SERVICE_ENABLE_PIAWARE=false"
      - "SERVICE_ENABLE_FR24FEED=false"
      - "SERVICE_ENABLE_HTTP=false"
      - "SERVICE_ENABLE_IMPORT_OVER_NETCAT=false"
      - "SERVICE_ENABLE_ADSBEXCHANGE=false"
      - "SERVICE_ENABLE_PLANEFINDER=false"
      - "DUMP1090_ADDITIONAL_ARGS=--json-location-accuracy 2 --gain 49.6 --ppm 60 --net-bi-port 30004,30104"
```

Connected to all providers side:
```
      - "DUMP1090_REMOTE_HOST=<IP_OF_REMOTE_DUMP1090>"
      - "DUMP1090_ADDITIONAL_ARGS=--json-location-accuracy 2 --ppm 60 --net-bi-port 30004,30104 --net-only"
      - "SERVICE_ENABLE_IMPORT_OVER_NETCAT=true"
      - "DUMP1090_LOCAL_PORT=30004"
      - "DUMP1090_REMOTE_HOST=readsb"
      - "DUMP1090_REMOTE_PORT=30005"
```
