### ISSUE TITLE
Feature Request: Feed in to 360Radar

### ISSUE THREAD

**Issue by snerd9334** [Thom-x/docker-fr24feed-piaware-dump1090#168]
Feature Request to support feeding into 360Radar.co.uk (aka Low Flying Wales)

https://radar.lowflyingwales.co.uk/installing-the-mlat-client-on-a-raspberry-pi/

Thank you

**Comment by TomHom91** [comment]
@Thom-x, if you want, there is a docker example here: https://github.com/mikenye/docker-360radar
But, it was taking down as requested by the owners of 360radar.co.uk

**Comment by Thom-x** [comment]
If it was taken down by the owner, I don't really want to have it removed on my repo as well.
