### ISSUE TITLE
Error when starting container

### ISSUE THREAD

**Issue by robertscheib** [Thom-x/docker-fr24feed-piaware-dump1090#28]
## Specifications

  - Image hash or version: 
  - Platform: Raspberry Pi 3
  - Subsystem: Raspberry Pi OS

## Expected Behavior
FR24Feed and piaware to run and begin sharing

## Actual Behavior

Container starts up and then shuts down. Portainer is showing the following error in the log.  It repeats for every attempt to restart, it includes nothing else.

standard_init_linux.go:211: exec user process caused "exec format error"

I have included what I believe to be necessary screenshots. 

![Container Details](https://user-images.githubusercontent.com/35755161/87595883-dfd65500-c6b4-11ea-85e1-9fd3d9d04967.png)
![Dockerfile Details](https://user-images.githubusercontent.com/35755161/87595884-e06eeb80-c6b4-11ea-9ad8-d606c6497831.png)
![Image Details](https://user-images.githubusercontent.com/35755161/87595885-e06eeb80-c6b4-11ea-96b1-1755850a9a4c.png)
![Image Layers](https://user-images.githubusercontent.com/35755161/87595886-e06eeb80-c6b4-11ea-9fa7-11879f978679.png)

## Steps to Reproduce the Problem

  1. Start container in Portainer
  2. Monitor start progress
  3. Check log for additional error reference (show above in "Actual Behavior"

**Comment by Thom-x** [comment]
You cannot run this image version with a Raspberry Pi 3, you need to build it yourself.

With docker hub it's not possible to build images for arm architecture. The only solution right now is to build it yourself.

`docker build -t myimagename .`

**Comment by e2jk** [comment]
@robertscheib FYI thomx is apparently now pushing his images to the Docker Hub not only for `linux/amd64`, but also `linux/arm/v6` and `linux/arm/v7` - so I've been running this image on a Raspberry Pi 1B (yes, old ;) ) without issues or having to compile it myself (which would have been awfully slow).

**Comment by robertscheib** [comment]
> @robertscheib FYI thomx is apparently now pushing his images to the Docker Hub not only for `linux/amd64`, but also `linux/arm/v6` and `linux/arm/v7` - so I've been running this image on a Raspberry Pi 1B (yes, old ;) ) without issues or having to compile it myself (which would have been awfully slow).

Awesome, thanks for the update. I have to rebuild my Pi as the SS card just died.
