### ISSUE TITLE
dump1090-fa

### ISSUE THREAD

**Issue by SaturnusDJ** [Thom-x/docker-fr24feed-piaware-dump1090#5]
Seems like https://github.com/flightaware/dump1090 is the successor of dump1090-mutability?

**Comment by SaturnusDJ** [comment]
I think it looks like this: http://mtg.getmyip.com:747/tar1090/
Usability improvements. 👍

**Comment by Thom-x** [comment]
Fixed d329c4ed2eac1b70b0897ab160aa157ec212e2c2

**Comment by SaturnusDJ** [comment]
Thanks. ARM update requested at https://github.com/dmorehouse/docker-raspberrypi-fr24feed-piaware-dump1090-mutability/pull/1. If no response then I guess it's time for me to learn some Docker.

**Comment by Thom-x** [comment]
Yep, I can't build it.
However it may be not so difficult to adapt my changes for Rpi.
