### ISSUE TITLE
[Suggestion] Publish data to more plane tracker websites

### ISSUE THREAD

**Issue by e2jk** [Thom-x/docker-fr24feed-piaware-dump1090#53]
(removing the default issue template, as this is not really an issue report but a question/suggestion)

Question: would there be interest to publish a receiver's data to more public plane tracker websites?
For example:
- [ADS-B Exchange](https://www.adsbexchange.com/how-to-feed/)
  - This one is new to me, seems interesting/non commercial, even its UI is very comparable to our local receiver's UIs : `tar1090`, see #52
- [OpenSky Network](https://opensky-network.org/community/projects/30-dump1090-feeder)
- [AirNav RadarBox](https://www.radarbox.com/sharing-data)
- [Plane Finder](https://planefinder.net/coverage/client)
- [ADSBHub](https://www.adsbhub.org/howtofeed.php)

**Comment by mike14-2** [comment]
I would be interested in that as well. Especially in RadarBox
