### ISSUE TITLE
[Suggestion] script.js circle values through env vars

### ISSUE THREAD

**Issue by rainoko** [Thom-x/docker-fr24feed-piaware-dump1090#57]
Following values should be configurable through env.

DefaultSiteCirclesCount = 3;
DefaultSiteCirclesBaseDistance = 100;
DefaultSiteCirclesInterval = 50;

**Comment by Thom-x** [comment]
I'm not sure if it is very useful, these properties are available on the UI and persisted after a refresh.

![image](https://user-images.githubusercontent.com/6797195/116043253-b862de80-a66f-11eb-89ef-e8f4bf01cbca.png)
