### ISSUE TITLE
Upgrade to V6.0 problem

### ISSUE THREAD

**Issue by DanielMcAssey** [Thom-x/docker-fr24feed-piaware-dump1090#63]
Issue with new update, getting the following error when launching. It was working before the upgrade.

> warning: /etc/piaware.conf: failed to read config file: error reading "file3": illegal operation on a directory
>
>piaware (process 361) is shutting down because it received a shutdown signal (SIGTERM) from the system...
>piaware (process 361) is exiting...
>[s6-finish] sending all processes the KILL signal and exiting.

**Comment by Thom-x** [comment]
Hello,

Are you mounting a volume with `/etc/piaware.conf `? It appears to be a folder. If so, don't mount any volume.

**Comment by Thom-x** [comment]
See https://github.com/Thom-x/docker-fr24feed-piaware-dump1090/issues/56#issuecomment-815842310

**Comment by DanielMcAssey** [comment]
Spot on. That solved it. Thank you
