### ISSUE TITLE
MLAT not working for FlightAware

### ISSUE THREAD

**Issue by Munger** [Thom-x/docker-fr24feed-piaware-dump1090#68]
## Specifications

  - Image hash or version: 3b511184a1cb
  - Platform: Raspberry Pi
  - Subsystem:

## Actual Behavior
FlightRadar24 is receiving MLAT from my station but FlightAware isn't.

**Comment by Thom-x** [comment]
Do you have any error, what is flight aware saying about MLAT sync ? I really don't know what could be wrong 😕
