### ISSUE TITLE
Unable to set Plane Finder

### ISSUE THREAD

**Issue by Faultiness** [Thom-x/docker-fr24feed-piaware-dump1090#83]
## Specifications

  - Image hash or version: 1.11.0
  - Platform: FriendlyARM NanoPi R4S
  - Subsystem: Armbian 21.08.8 Focal

## Steps to Reproduce the Problem

  1. Update the image and run the command as suggested in the readme file.
  2. Unexpected output `/run/s6/basedir/scripts/rc.init: 35: /run/s6/basedir/scripts/rc.init: /planefinder/pfclient: not found`

**Comment by Thom-x** [comment]
Are you using `SERVICE_ENABLE_PLANEFINDER=true` ?

If you run:
```
docker run -it --rm \
	-e "SERVICE_ENABLE_DUMP1090=false" \
	-e "SERVICE_ENABLE_HTTP=false" \
	-e "SERVICE_ENABLE_FR24FEED=false" \
	-e "SERVICE_ENABLE_PIAWARE=false" \
	thomx/fr24feed-piaware ls /planefinder/
```
What is the result ?

If you run:
```
docker run -it --rm \
	-e "SERVICE_ENABLE_DUMP1090=false" \
	-e "SERVICE_ENABLE_HTTP=false" \
	-e "SERVICE_ENABLE_FR24FEED=false" \
	-e "SERVICE_ENABLE_PIAWARE=false" \
	thomx/fr24feed-piaware dpkg --print-architecture
```
What is the result ?

**Comment by Thom-x** [comment]
Ok funny and what about: 

```
docker run -it --rm \
	-e "SERVICE_ENABLE_DUMP1090=false" \
	-e "SERVICE_ENABLE_HTTP=false" \
	-e "SERVICE_ENABLE_FR24FEED=false" \
	-e "SERVICE_ENABLE_PIAWARE=false" \
	thomx/fr24feed-piaware /planefinder/pfclient
```

(probably `/planefinder/pfclient: not found` 😄)

**Comment by Faultiness** [comment]
Yeah you are right. It returns `/run/s6/basedir/scripts/rc.init: 35: /run/s6/basedir/scripts/rc.init: /planefinder/pfclient: not found`.

**Comment by Thom-x** [comment]
Either the client is corrupted or not compatible with your architecture. But I cannot test it (I'm on amd64).
The client is downloaded from here =>https://planefinder.net/coverage/client
Could you try to download the tarball and run the client (on the host or within the image) ?

**Comment by Thom-x** [comment]
@Faultiness Could you test with image tag `docker pull thomx/fr24feed-piaware:PR-84` if it's better?

**Comment by Thom-x** [comment]
And with:

```
docker run -it --rm \
	-e "SERVICE_ENABLE_DUMP1090=false" \
	-e "SERVICE_ENABLE_HTTP=false" \
	-e "SERVICE_ENABLE_FR24FEED=false" \
	-e "SERVICE_ENABLE_PIAWARE=false" \
	thomx/fr24feed-piaware:PR-84 qemu-arm-static /planefinder/pfclient --version
```

**Comment by Faultiness** [comment]
Aha I got this `/lib/ld-linux-armhf.so.3: No such file or directory`.

**Comment by Thom-x** [comment]
OK with:

```
docker run -it --rm \
	-e "SERVICE_ENABLE_DUMP1090=false" \
	-e "SERVICE_ENABLE_HTTP=false" \
	-e "SERVICE_ENABLE_FR24FEED=false" \
	-e "SERVICE_ENABLE_PIAWARE=false" \
	thomx/fr24feed-piaware:PR-84 apt update && apt install lsb-base:armhf -y && qemu-arm-static /planefinder/pfclient --version

```

**Comment by Faultiness** [comment]
Ok and I got...
```
Note, selecting 'lsb-base' instead of 'lsb-base:armhf'
lsb-base is already the newest version (11.1.0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
zsh: command not found: qemu-arm-static
```

**Comment by Thom-x** [comment]
I updated the command, it is trying to do it locally :D

**Comment by Faultiness** [comment]
So, Hmmm, anything I can do for now? Or waiting for your good news 😁

**Comment by Faultiness** [comment]
Now I got
```
Note, selecting 'lsb-base' instead of 'lsb-base:armhf'
lsb-base is already the newest version (10.2019051400).
lsb-base set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
/lib/ld-linux-armhf.so.3: No such file or directory
```

**Comment by Faultiness** [comment]
Hmm and the output was
```
Note, selecting 'lsb-base' instead of 'lsb-base:armhf'
lsb-base is already the newest version (10.2019051400).
lsb-base set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
/bin/bash: ldconfig: command not found
```

**Comment by Thom-x** [comment]
```
docker run -it --rm \
	-e "SERVICE_ENABLE_DUMP1090=false" \
	-e "SERVICE_ENABLE_HTTP=false" \
	-e "SERVICE_ENABLE_FR24FEED=false" \
	-e "SERVICE_ENABLE_PIAWARE=false" \
	thomx/fr24feed-piaware:PR-84 /bin/bash -c "dpkg --add-architecture armhf && apt update && apt install lsb-base:armhf -y && /sbin/ldconfig && qemu-arm-static /planefinder/pfclient --version"
```

**Comment by Faultiness** [comment]
still `/lib/ld-linux-armhf.so.3: No such file or directory`

**Comment by Thom-x** [comment]
I don't know what to do :/ 
It's something with arm64 and armhf. But I really don't know how it works.

**Comment by Faultiness** [comment]
Don't get upset dude. Your repo is the best one I've ever used. 👍
I've tried [sdr-enthusiasts/docker-planefinder](https://github.com/sdr-enthusiasts/docker-planefinder), and it works fine on my device. Maybe there is just some tiny bug that we ignored?

**Comment by Thom-x** [comment]
Yep probably. I also used it to add planefinder.

Let's try:
docker run -it --rm \
	-e "SERVICE_ENABLE_DUMP1090=false" \
	-e "SERVICE_ENABLE_HTTP=false" \
	-e "SERVICE_ENABLE_FR24FEED=false" \
	-e "SERVICE_ENABLE_PIAWARE=false" \
	thomx/fr24feed-piaware:PR-84 /bin/bash -c "ls -la /lib/arm-linux-gnueabihf/ld-linux.so.3 && /lib/ld-linux.so.3"

**Comment by Thom-x** [comment]
It must be somewhere else, if we do a symb link to `/lib/ld-linux-armhf.so.3` it should fix the issue.
Try looking in `/lib/ld-linux.so.3` or `/lib64/ld-linux.so.3` or something like that.

**Comment by Faultiness** [comment]
Aha it says `/planefinder/pfclient: Invalid ELF image for this architecture`

**Comment by Thom-x** [comment]
Ok 😄
I'm trying a new build to see if it is better.
I'll let you know when it's ready.

**Comment by Faultiness** [comment]
Nice~ Waiting for your good news🎉

**Comment by Thom-x** [comment]
What about ?
```
docker run -it --rm \
	-e "SERVICE_ENABLE_DUMP1090=false" \
	-e "SERVICE_ENABLE_HTTP=false" \
	-e "SERVICE_ENABLE_FR24FEED=false" \
	-e "SERVICE_ENABLE_PIAWARE=false" \
	thomx/fr24feed-piaware:PR-84 /bin/bash -c "ls -la /lib/aarch64-linux-gnu/"
```

**Comment by Thom-x** [comment]
This one is the one I'm interested in `ld-linux-aarch64.so.1`

```
docker run -it --rm \
	-e "SERVICE_ENABLE_DUMP1090=false" \
	-e "SERVICE_ENABLE_HTTP=false" \
	-e "SERVICE_ENABLE_FR24FEED=false" \
	-e "SERVICE_ENABLE_PIAWARE=false" \
	thomx/fr24feed-piaware:PR-84 /bin/bash -c "ln -s /lib/aarch64-linux-gnu/ld-linux-aarch64.so.1 /lib/ld-linux-armhf.so.3 && qemu-arm-static /planefinder/pfclient --version"
```

**Comment by Faultiness** [comment]
It returns `/lib/ld-linux-armhf.so.3: Invalid ELF image for this architecture`

**Comment by Thom-x** [comment]
Im' out of idea, let's see the new build (I changed the order of `dpkg --add-architecture armhf`) 🤞

**Comment by Thom-x** [comment]
You can try to pull the same tag again.

**Comment by Faultiness** [comment]
Nice dude it works! 🎉🎉🎉

**Comment by Thom-x** [comment]
Cool 🎉
Could you try again (same tag)?
I've done some refactoring/cleaning.
