### ISSUE TITLE
Max Range Plot

### ISSUE THREAD

**Issue by viritt** [Thom-x/docker-fr24feed-piaware-dump1090#87]
Upon looking at the cover, ![image](https://user-images.githubusercontent.com/7139714/162051992-b04f7bcd-48cb-4613-9670-1e04867dd96f.png)

Is that a max range plot or is it the theoretical antenna range from heywhatsthat terrain-limit rings ?

How could I set it up in your image??

**Comment by Thom-x** [comment]
It's the theoretical antenna range from heywhatsthat terrain-limit rings. Everything is explained in the [README](https://github.com/Thom-x/docker-fr24feed-piaware-dump1090#terrain-limit-rings-optional).
